export enum routes {
    ONBOARD = 'ONBOARD',
    LOBBY = 'LOBBY',
    SIGN_IN = 'SIGN_IN',
    CREATE_ACCOUNT = 'CREATE_ACCOUNT',

    BOTTOM_TAB = 'BOTTOM_TAB',
    HOME = 'HOME',
    SAVE_JOB = 'SAVE_JOB',
    PROFILE = 'PROFILE',
    MESSAGES = 'MESSAGES',
    APPLICATIONS = 'APPLICATIONS',

    NOTIFICATION = 'NOTIFICATION',
    SEARCH = 'SEARCH',
    EDIT_PROFILE = 'EDIT_PROFILE',
    JOB_DETAIL = 'JOB_DETAIL',
    APPLICATION_DETAIL = 'APPLICATION_DETAIL',
    SETTING = 'SETTING',
}
